import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import os

# Set visual style
sns.set_theme(style="white")

def create_visualizations(csv_file):
    if not os.path.exists(csv_file):
        print(f"File {csv_file} not found. Skipping.")
        return None

    # Load data
    df = pd.read_csv(csv_file)
    dataset_name = df['dataset_name'].iloc[0]
    print(f"Processing visualizations for: {dataset_name}")

    # 1. ACCURACY HEATMAP [cite: 912-915]
    # Pivot: Y=Fraction, X=Repeats, Values=Accuracy
    pivot_table = df.pivot(index="training_fraction_used", 
                           columns="augmentation_repeat_level", 
                           values="test_accuracy")
    
    # Sort so 100% fraction is at the top
    pivot_table = pivot_table.sort_index(ascending=False)

    plt.figure(figsize=(10, 8))
    sns.heatmap(pivot_table, annot=True, fmt=".1f", cmap="magma", 
                cbar_kws={'label': 'Test Accuracy (%)'})
    plt.title(f"Heatmap: Accuracy by Fraction vs Repeats\nDataset: {dataset_name}")
    plt.xlabel("Augmentation Repeat Level")
    plt.ylabel("Training Data Fraction")
    plt.savefig(f"heatmap_{dataset_name}.png", bbox_inches='tight', dpi=300)
    plt.close()

    # 2. BEST MODEL CONFUSION MATRIX [cite: 908, 1125]
    # Identify the best performing run in the sweep
    best_run = df.loc[df['test_accuracy'].idxmax()]
    
    # Reconstruct matrix from stored TN, FP, FN, TP
    cm_data = np.array([[best_run['tn'], best_run['fp']], 
                        [best_run['fn'], best_run['tp']]])
    
    # Parse class names from string back to list
    classes = eval(best_run['class_names']) 

    plt.figure(figsize=(7, 6))
    sns.heatmap(cm_data, annot=True, fmt="d", cmap="Blues", 
                xticklabels=classes, yticklabels=classes)
    plt.title(f"Confusion Matrix: Best Performing Model ({dataset_name})\n"
              f"Fraction: {best_run['training_fraction_used']} | Repeats: {best_run['augmentation_repeat_level']}")
    plt.ylabel("Actual Category")
    plt.xlabel("Predicted Category")
    plt.savefig(f"confusion_matrix_{dataset_name}.png", bbox_inches='tight', dpi=300)
    plt.close()

    # 3. TRAINING TIME VS ACCURACY (Trade-off Analysis) [cite: 627-630, 951]
    plt.figure(figsize=(10, 6))
    sns.scatterplot(data=df, x="training_time_sec", y="test_accuracy", 
                    hue="training_fraction_used", size="augmentation_repeat_level", 
                    palette="viridis", sizes=(50, 200))
    plt.title(f"Trade-off: Training Time vs Accuracy ({dataset_name})")
    plt.xlabel("Training Time (Seconds)")
    plt.ylabel("Test Accuracy (%)")
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', title="Legend")
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.savefig(f"tradeoff_{dataset_name}.png", bbox_inches='tight', dpi=300)
    plt.close()

    return df

def generate_comparison_graph(all_dfs):
    """Creates a comparison across different datasets [cite: 917-922]."""
    if not all_dfs: return
    
    combined = pd.concat(all_dfs)
    
    plt.figure(figsize=(12, 7))
    sns.lineplot(data=combined, x="augmentation_repeat_level", y="test_accuracy", 
                 hue="dataset_name", style="dataset_name", markers=True, dashes=False)
    plt.title("Comparison: Impact of Augmentation Repeats Across Datasets\n(Average across all fractions)")
    plt.xlabel("Augmentation Repeat Level")
    plt.ylabel("Mean Test Accuracy (%)")
    plt.grid(True, alpha=0.3)
    plt.savefig("comparison_across_datasets.png", bbox_inches='tight', dpi=300)
    plt.close()

if __name__ == "__main__":
    # List of result files generated by sweep_trainer.py
    results_files = ["results_carpet.csv", "results_toothbrush.csv", "results_cat_dog.csv"]
    
    dataframes = []
    for f in results_files:
        df = create_visualizations(f)
        if df is not None:
            dataframes.append(df)
    
    # Generate the final comparison across all three datasets
    generate_comparison_graph(dataframes)
    print("\nAll visualizations (Heatmaps, CMs, and Comparison Graphs) generated successfully.")